# Generated by Django 5.2 on 2026-03-13 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('cancelled', '已取消'), ('refunded', '已退款'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='订单状态')),
                ('payment_method', models.CharField(blank=True, choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('balance', '余额支付')], max_length=20, verbose_name='支付方式')),
                ('paid_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('expired_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='membership.membershipplan', verbose_name='会员套餐')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('payment_no', models.CharField(max_length=64, unique=True, verbose_name='支付流水号')),
                ('third_party_no', models.CharField(blank=True, max_length=128, verbose_name='第三方支付号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('channel', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付')], max_length=20, verbose_name='支付渠道')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('success', '支付成功'), ('failed', '支付失败'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='支付状态')),
                ('paid_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('refund_no', models.CharField(max_length=64, unique=True, verbose_name='退款单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='退款金额')),
                ('reason', models.TextField(verbose_name='退款原因')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '退款成功'), ('failed', '退款失败')], default='pending', max_length=20, verbose_name='退款状态')),
                ('refunded_time', models.DateTimeField(blank=True, null=True, verbose_name='退款时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.order', verbose_name='订单')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='支付记录')),
            ],
            options={
                'verbose_name': '退款记录',
                'verbose_name_plural': '退款记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额')),
                ('frozen_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='冻结余额')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='累计收入')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='累计支出')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户钱包',
                'verbose_name_plural': '用户钱包',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('transaction_no', models.CharField(max_length=32, unique=True, verbose_name='交易号')),
                ('transaction_type', models.CharField(choices=[('recharge', '充值'), ('consume', '消费'), ('refund', '退款'), ('income', '收入')], max_length=20, verbose_name='交易类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='变动前余额')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='变动后余额')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='payments.order', verbose_name='关联订单')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.wallet', verbose_name='钱包')),
            ],
            options={
                'verbose_name': '钱包交易记录',
                'verbose_name_plural': '钱包交易记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
