import type { RouteRecordRaw } from "vue-router";

export const toolRoutes: RouteRecordRaw[] = [
  {
    path: "/tools",
    name: "ToolsHome",
    component: () => import("@features/tools/pages/ToolsHomePage.vue"),
    meta: { title: "开发工具" },
  },
  {
    path: "/tools/image-editor",
    name: "ImageEditor",
    component: () => import("@/pages/tools/ImageEditorPro.vue"),
    meta: { title: "图片编辑器" },
  },
  {
    path: "/tools/encrypt",
    name: "EncryptTool",
    component: () => import("@features/tools/pages/EncryptToolPage.vue"),
    meta: { title: "加密解密" },
  },
  {
    path: "/tools/rc4",
    name: "Rc4Tool",
    component: () => import("@features/tools/pages/EncryptToolPage.vue"),
    meta: { title: "RC4 加密解密", encryptTab: "rc4" },
  },
  {
    path: "/tools/sm3",
    name: "Sm3Tool",
    component: () => import("@features/tools/pages/EncryptToolPage.vue"),
    meta: { title: "SM3 国密摘要", encryptTab: "sm3" },
  },
  {
    path: "/tools/encode",
    name: "EncodeTool",
    component: () => import("@features/tools/pages/EncodeToolPage.vue"),
    meta: { title: "编码解码" },
  },
  {
    path: "/tools/json-formatter",
    name: "JsonFormatter",
    component: () => import("@features/tools/pages/JsonFormatterPage.vue"),
    meta: { title: "JSON格式化" },
  },
  {
    path: "/tools/uuid-generator",
    name: "UuidGenerator",
    component: () => import("@/pages/tools/UuidGenerator.vue"),
    meta: { title: "UUID生成器" },
  },
  {
    path: "/tools/timestamp-converter",
    name: "TimestampConverter",
    component: () => import("@features/tools/pages/TimestampConverterPage.vue"),
    meta: { title: "时间戳转换" },
  },
  {
    path: "/tools/color-picker",
    name: "ColorPicker",
    component: () => import("@/pages/tools/ColorPicker.vue"),
    meta: { title: "颜色拾取器" },
  },
  {
    path: "/tools/markdown-preview",
    name: "MarkdownPreview",
    component: () => import("@/pages/tools/MarkdownPreview.vue"),
    meta: { title: "Markdown 预览" },
  },
  {
    path: "/tools/password-generator",
    name: "PasswordGenerator",
    component: () => import("@/pages/tools/PasswordGenerator.vue"),
    meta: { title: "密码生成器" },
  },
  {
    path: "/tools/text-diff",
    name: "TextDiff",
    component: () => import("@/pages/tools/TextDiff.vue"),
    meta: { title: "文本对比" },
  },
  {
    path: "/tools/json-diff",
    name: "JsonDiff",
    component: () => import("@/pages/tools/JsonDiff.vue"),
    meta: { title: "JSON 对比" },
  },
  {
    path: "/tools/image-compressor",
    name: "ImageCompressor",
    component: () => import("@/pages/tools/ImageCompressor.vue"),
    meta: { title: "图片压缩" },
  },
  {
    path: "/tools/base-converter",
    name: "BaseConverter",
    component: () => import("@/pages/tools/BaseConverter.vue"),
    meta: { title: "进制转换" },
  },
  {
    path: "/tools/regex-tester",
    name: "RegexTester",
    component: () => import("@features/tools/pages/RegexTesterPage.vue"),
    meta: { title: "正则测试器" },
  },
  {
    path: "/tools/hash-generator",
    name: "HashGenerator",
    component: () => import("@/pages/tools/HashGenerator.vue"),
    meta: { title: "哈希生成器" },
  },
  {
    path: "/tools/json-to-sql",
    name: "JsonToSql",
    component: () => import("@/pages/tools/JsonToSql.vue"),
    meta: { title: "JSON 转 SQL" },
  },
  {
    path: "/tools/curl-converter",
    name: "CurlConverter",
    component: () => import("@/pages/tools/CurlConverter.vue"),
    meta: { title: "curl 转代码" },
  },
  {
    path: "/tools/curl-to-requests",
    redirect: "/tools/curl-converter",
  },
  {
    path: "/tools/code-formatter",
    name: "CodeFormatter",
    component: () => import("@/pages/tools/CodeFormatter.vue"),
    meta: { title: "JS/HTML 格式化" },
  },
  {
    path: "/tools/js-formatter",
    name: "JsFormatter",
    component: () => import("@/pages/tools/CodeFormatter.vue"),
    meta: { title: "JS 格式化", codeMode: "javascript" },
  },
  {
    path: "/tools/js-obfuscator",
    name: "JsObfuscator",
    component: () => import("@/pages/tools/CodeFormatter.vue"),
    meta: { title: "JS 混淆解码", codeMode: "obfuscator" },
  },
  {
    path: "/tools/html-formatter",
    name: "HtmlFormatter",
    component: () => import("@/pages/tools/CodeFormatter.vue"),
    meta: { title: "HTML 格式化", codeMode: "html" },
  },
  {
    path: "/tools/css-formatter",
    name: "CssFormatter",
    component: () => import("@/pages/tools/CodeFormatter.vue"),
    meta: { title: "CSS 格式化", codeMode: "css" },
  },
  {
    path: "/tools/header-formatter",
    name: "HeaderFormatter",
    component: () => import("@/pages/tools/CrawlerToolkit.vue"),
    meta: { title: "Header 格式化", crawlerMode: "headers" },
  },
  {
    path: "/tools/cookie-formatter",
    name: "CookieFormatter",
    component: () => import("@/pages/tools/CrawlerToolkit.vue"),
    meta: { title: "Cookie 格式化", crawlerMode: "cookies" },
  },
  {
    path: "/tools/dict-formatter",
    name: "DictFormatter",
    component: () => import("@/pages/tools/CrawlerToolkit.vue"),
    meta: { title: "Dict 转换", crawlerMode: "dict" },
  },
  {
    path: "/tools/url-params",
    name: "UrlParams",
    component: () => import("@/pages/tools/CrawlerToolkit.vue"),
    meta: { title: "URL 参数提取", crawlerMode: "url" },
  },
  {
    path: "/tools/url-codec",
    name: "UrlCodec",
    component: () => import("@/pages/tools/CrawlerToolkit.vue"),
    meta: { title: "URL 编解码", crawlerMode: "codec" },
  },
  {
    path: "/tools/html-renderer",
    name: "HtmlRenderer",
    component: () => import("@/pages/tools/CrawlerToolkit.vue"),
    meta: { title: "HTML 渲染", crawlerMode: "html" },
  },
  {
    path: "/tools/text-decoder",
    name: "TextDecoder",
    component: () => import("@/pages/tools/CrawlerToolkit.vue"),
    meta: { title: "文本解码", crawlerMode: "decoder" },
  },
  {
    path: "/tools/code-share",
    name: "CodeShare",
    component: () => import("@/pages/tools/CrawlerToolkit.vue"),
    meta: { title: "代码分享", crawlerMode: "share" },
  },
  {
    path: "/tools/base64-image",
    name: "Base64Image",
    component: () => import("@/pages/tools/Base64ImageTool.vue"),
    meta: { title: "Base64 图片" },
  },
];
