# Generated by Django 6.0.3 on 2026-03-13 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='广告图片')),
                ('link', models.URLField(blank=True, null=True, verbose_name='链接地址')),
                ('position', models.CharField(choices=[('header', '顶部'), ('sidebar', '侧边栏'), ('footer', '底部'), ('article_top', '文章顶部'), ('article_bottom', '文章底部')], default='sidebar', max_length=20, verbose_name='广告位置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击次数')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
                'ordering': ['position', 'sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-is_pinned', 'sort', '-publish_time'],
            },
        ),
    ]
