# Generated by Django 5.2 on 2026-03-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '网站配置',
                'verbose_name_plural': '网站配置',
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('bar', '公告栏'), ('modal', '弹窗')], default='bar', max_length=20, verbose_name='公告类型'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='auto_close',
            field=models.BooleanField(default=False, verbose_name='是否自动关闭'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='auto_close_time',
            field=models.IntegerField(default=30, help_text='多少秒后自动关闭', verbose_name='自动关闭时间(秒)'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='show_delay',
            field=models.IntegerField(default=5, help_text='弹窗显示后多少秒可以关闭，0表示立即可以关闭', verbose_name='延迟关闭时间(秒)'),
        ),
    ]
