# Generated by Django 5.2 on 2026-03-13 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='权益名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='权益代码')),
                ('benefit_type', models.CharField(choices=[('feature', '功能权限'), ('quota', '数量配额'), ('discount', '折扣优惠'), ('other', '其他')], default='feature', max_length=20, verbose_name='权益类型')),
                ('description', models.TextField(blank=True, verbose_name='权益描述')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='图标')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '会员权益',
                'verbose_name_plural': '会员权益',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('description', models.TextField(blank=True, verbose_name='套餐描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('duration_days', models.IntegerField(help_text='0表示永久', verbose_name='有效期(天)')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='权益列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_popular', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('badge_text', models.CharField(blank=True, max_length=50, verbose_name='角标文字')),
            ],
            options={
                'verbose_name': '会员套餐',
                'verbose_name_plural': '会员套餐',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否有效')),
                ('is_lifetime', models.BooleanField(default=False, verbose_name='是否永久会员')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_memberships', to='membership.membershipplan', verbose_name='会员套餐')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户会员',
                'verbose_name_plural': '用户会员',
            },
        ),
        migrations.CreateModel(
            name='PlanBenefitRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('value', models.CharField(blank=True, help_text='如配额数量、折扣比例等', max_length=200, verbose_name='权益值')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_relations', to='membership.membershipbenefit', verbose_name='会员权益')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_relations', to='membership.membershipplan', verbose_name='会员套餐')),
            ],
            options={
                'verbose_name': '套餐权益关联',
                'verbose_name_plural': '套餐权益关联',
                'unique_together': {('plan', 'benefit')},
            },
        ),
    ]
