# Generated by Django 5.2 on 2026-03-07 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', '图片'), ('file', '文件'), ('video', '视频')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '媒体资源',
                'verbose_name_plural': '媒体资源',
                'db_table': 'media_asset',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'media_type'], name='media_asset_user_id_4a0cd2_idx'), models.Index(fields=['created_at'], name='media_asset_created_8f10ab_idx')],
            },
        ),
    ]
