"""
Django settings for Myblob project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-test-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "core",
    "accounts",
    "blog",
    "comments",
    "interactions",
    "mediaapp",
    "membership",
    "payments",
    "social",
    "security",
    "website",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Myblob.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Myblob.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "blog",
        "USER": "postgres",
        "PASSWORD": "123456",
        "HOST": "127.0.0.1",
        "PORT": "5432",
        "CONN_MAX_AGE": 0,  # 禁用持久连接，避免连接数过多
        "CONN_HEALTH_CHECKS": True,  # 启用连接健康检查
        "OPTIONS": {
            'connect_timeout': 5,  # 连接超时时间（秒）
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "zh-hans"
TIME_ZONE = "Asia/Shanghai"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.User"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "Myblob.authentication.OptionalTokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
]

# 邮箱配置
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# 阿里云短信配置
ALIYUN_ACCESS_KEY_ID = os.getenv("ALIYUN_ACCESS_KEY_ID", "")
ALIYUN_ACCESS_KEY_SECRET = os.getenv("ALIYUN_ACCESS_KEY_SECRET", "")
ALIYUN_SMS_SIGN_NAME = os.getenv("ALIYUN_SMS_SIGN_NAME", "MyBlob")
ALIYUN_SMS_TEMPLATE_CODE = os.getenv("ALIYUN_SMS_TEMPLATE_CODE", "")

# 第三方登录配置
THIRD_PARTY_LOGIN = {
    "wechat": {
        "app_id": os.getenv("WECHAT_APP_ID", ""),
        "app_secret": os.getenv("WECHAT_APP_SECRET", ""),
        "redirect_uri": "http://localhost:3001/auth/callback/wechat",
    },
    "qq": {
        "app_id": os.getenv("QQ_APP_ID", ""),
        "app_secret": os.getenv("QQ_APP_SECRET", ""),
        "redirect_uri": "http://localhost:3001/auth/callback/qq",
    },
    "weibo": {
        "app_id": os.getenv("WEIBO_APP_ID", ""),
        "app_secret": os.getenv("WEIBO_APP_SECRET", ""),
        "redirect_uri": "http://localhost:3001/auth/callback/weibo",
    },
    "github": {
        "client_id": os.getenv("GITHUB_CLIENT_ID", ""),
        "client_secret": os.getenv("GITHUB_CLIENT_SECRET", ""),
        "redirect_uri": "http://localhost:3001/auth/callback/github",
    }
}

JAZZMIN_SETTINGS = {
    "site_title": "MyBlob 管理后台",
    "site_header": "MyBlob",
    "site_brand": "MyBlob",
    "site_logo": None,
    "site_logo_classes": "img-circle",
    "welcome_sign": "欢迎来到 MyBlob 管理后台",
    "copyright": "MyBlob © 2026",
    "search_model": ["auth.User", "blog.Post", "accounts.User"],
    "user_avatar": None,
    
    "topmenu_links": [
        {"name": "首页", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "文章管理", "url": "admin:blog_post_changelist", "permissions": ["blog.view_post"]},
        {"name": "用户管理", "url": "admin:accounts_user_changelist", "permissions": ["accounts.view_user"]},
    ],
    
    "usermenu_links": [
        {"name": "个人资料", "url": "admin:accounts_user_changelist", "permissions": ["accounts.view_user"]},
        {"model": "auth.user"},
    ],
    
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "blog", "accounts", "comments", "interactions", "mediaapp", "core", "membership", "payments", "social", "security", "website"],
    
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "blog": "fas fa-blog",
        "blog.Post": "fas fa-file-alt",
        "blog.Category": "fas fa-folder",
        "blog.Tag": "fas fa-tags",
        "accounts": "fas fa-user-circle",
        "accounts.User": "fas fa-user",
        "accounts.UserProfile": "fas fa-id-card",
        "accounts.Follow": "fas fa-heart",
        "comments": "fas fa-comments",
        "comments.Comment": "fas fa-comment",
        "comments.CommentLike": "fas fa-thumbs-up",
        "interactions": "fas fa-bell",
        "interactions.Notification": "fas fa-bell",
        "interactions.Like": "fas fa-thumbs-up",
        "interactions.Bookmark": "fas fa-bookmark",
        "mediaapp": "fas fa-images",
        "mediaapp.Media": "fas fa-image",
        "core": "fas fa-cogs",
        "core.SiteConfig": "fas fa-sliders-h",
        "core.Announcement": "fas fa-bullhorn",
        "core.Ad": "fas fa-ad",
        "membership": "fas fa-star",
        "membership.MembershipPlan": "fas fa-crown",
        "membership.UserMembership": "fas fa-user-check",
        "payments": "fas fa-credit-card",
        "payments.Order": "fas fa-shopping-cart",
        "payments.Wallet": "fas fa-wallet",
        "payments.Transaction": "fas fa-exchange-alt",
        "social": "fas fa-share-alt",
        "social.SocialLogin": "fas fa-sign-in-alt",
        "security": "fas fa-shield-alt",
        "security.SecurityConfig": "fas fa-lock",
        "security.EmailConfig": "fas fa-envelope",
        "security.SmsConfig": "fas fa-sms",
        "security.VerificationLog": "fas fa-history",
        "website": "fas fa-globe",
    },
    
    "default_icon_parents": "fas fa-chevron-right",
    "default_icon_children": "fas fa-circle",
    
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible", 
        "auth.group": "vertical_tabs",
        "accounts.user": "collapsible",
        "blog.post": "horizontal_tabs",
    },
    "language_chooser": False,
    "show_custom_links": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-indigo",
    "navbar": "navbar-indigo navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "default",
    "default_theme_mode": "auto",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}
