# Generated by Django 5.2 on 2026-03-13 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '关注',
                'verbose_name_plural': '关注',
                'db_table': 'accounts_follow',
                'indexes': [models.Index(fields=['follower'], name='accounts_fo_followe_7c063a_idx'), models.Index(fields=['following'], name='accounts_fo_followi_b590bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='uniq_follower_following')],
            },
        ),
    ]
