# Generated by Django 5.2 on 2026-03-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('mediaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('article', '文章'), ('note', '笔记'), ('video', '视频')], default='note', max_length=20, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_posts', to='mediaapp.mediaasset'),
        ),
    ]
