# Generated by Django 5.2 on 2026-03-13 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code_enabled', models.BooleanField(default=True, verbose_name='启用验证码')),
                ('verification_code_length', models.IntegerField(default=6, verbose_name='验证码长度')),
                ('verification_code_expire_seconds', models.IntegerField(default=300, verbose_name='验证码过期时间(秒)')),
                ('anti_spider_enabled', models.BooleanField(default=True, verbose_name='启用反爬虫')),
                ('request_limit_per_minute', models.IntegerField(default=60, verbose_name='每分钟请求限制')),
                ('request_limit_per_hour', models.IntegerField(default=1000, verbose_name='每小时请求限制')),
                ('sso_enabled', models.BooleanField(default=True, verbose_name='启用单点登录')),
                ('max_sessions', models.IntegerField(default=1, verbose_name='最大同时在线数')),
                ('traffic_monitor_enabled', models.BooleanField(default=True, verbose_name='启用流量监控')),
                ('auto_block_enabled', models.BooleanField(default=True, verbose_name='自动封禁')),
                ('block_duration_seconds', models.IntegerField(default=3600, verbose_name='封禁时长(秒)')),
            ],
            options={
                'verbose_name': '安全配置',
                'verbose_name_plural': '安全配置',
            },
        ),
        migrations.CreateModel(
            name='IPBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('reason', models.TextField(verbose_name='封禁原因')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='封禁时间')),
                ('blocked_until', models.DateTimeField(verbose_name='解封时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='封禁人')),
            ],
            options={
                'verbose_name': 'IP封禁',
                'verbose_name_plural': 'IP封禁',
                'indexes': [models.Index(fields=['ip_address', 'is_active'], name='security_ip_ip_addr_fb42b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('path', models.CharField(max_length=500, verbose_name='请求路径')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('status_code', models.IntegerField(verbose_name='状态码')),
                ('response_time_ms', models.IntegerField(verbose_name='响应时间(毫秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_spider', models.BooleanField(default=False, verbose_name='是否爬虫')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '请求日志',
                'verbose_name_plural': '请求日志',
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='security_re_ip_addr_2440c4_idx'), models.Index(fields=['created_at'], name='security_re_created_ecce4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='会话Key')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户会话',
                'verbose_name_plural': '用户会话',
                'indexes': [models.Index(fields=['user', 'is_active'], name='security_us_user_id_9aa362_idx')],
            },
        ),
    ]
