# Generated by Django 5.2 on 2026-03-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('qq', 'QQ邮箱'), ('163', '163邮箱'), ('gmail', 'Gmail'), ('outlook', 'Outlook'), ('custom', '自定义')], default='qq', max_length=50, verbose_name='邮箱服务商')),
                ('host', models.CharField(blank=True, max_length=200, verbose_name='SMTP服务器')),
                ('port', models.IntegerField(default=587, verbose_name='端口')),
                ('use_tls', models.BooleanField(default=True, verbose_name='使用TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='使用SSL')),
                ('username', models.EmailField(max_length=254, verbose_name='邮箱账号')),
                ('password', models.CharField(max_length=200, verbose_name='密码/授权码')),
                ('from_email', models.EmailField(max_length=254, verbose_name='发件人邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '邮箱配置',
                'verbose_name_plural': '邮箱配置',
            },
        ),
        migrations.CreateModel(
            name='SmsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('aliyun', '阿里云'), ('tencent', '腾讯云'), ('custom', '自定义')], default='aliyun', max_length=50, verbose_name='短信服务商')),
                ('access_key_id', models.CharField(max_length=200, verbose_name='AccessKey ID')),
                ('access_key_secret', models.CharField(max_length=200, verbose_name='AccessKey Secret')),
                ('sign_name', models.CharField(default='MyBlob', max_length=50, verbose_name='签名')),
                ('template_code', models.CharField(max_length=50, verbose_name='模板CODE')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('daily_limit', models.IntegerField(default=100, verbose_name='每日发送限制')),
                ('hourly_limit', models.IntegerField(default=20, verbose_name='每小时发送限制')),
                ('minute_limit', models.IntegerField(default=5, verbose_name='每分钟发送限制')),
                ('same_ip_limit', models.IntegerField(default=3, verbose_name='同一IP限制')),
                ('same_receiver_limit', models.IntegerField(default=2, verbose_name='同一接收者限制')),
            ],
            options={
                'verbose_name': '短信配置',
                'verbose_name_plural': '短信配置',
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=200, verbose_name='接收者')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('code_type', models.CharField(choices=[('sms', '短信'), ('email', '邮箱')], max_length=10, verbose_name='类型')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('pending', '待发送')], default='pending', max_length=20, verbose_name='状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '验证码记录',
                'verbose_name_plural': '验证码记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receiver', 'created_at'], name='security_ve_receive_77a749_idx'), models.Index(fields=['ip_address', 'created_at'], name='security_ve_ip_addr_b049a8_idx'), models.Index(fields=['code_type', 'created_at'], name='security_ve_code_ty_9668d0_idx')],
            },
        ),
    ]
