# Generated by Django 5.2 on 2026-03-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_emailconfig_smsconfig_verificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityconfig',
            name='verification_code_method',
            field=models.CharField(choices=[('code', '数字验证码'), ('captcha', '图形验证码'), ('slider', '滑块验证码'), ('none', '无感验证'), ('auto', '自动选择')], default='code', help_text='注册时使用的验证方式', max_length=20, verbose_name='验证方式'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='verification_code_only_register',
            field=models.BooleanField(default=True, help_text='勾选后只有注册需要验证码，登录不需要', verbose_name='仅注册需要验证码'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='verification_code_type',
            field=models.CharField(choices=[('email', '邮箱验证码'), ('sms', '短信验证码'), ('auto', '自动选择（邮箱优先）')], default='email', help_text='默认使用邮箱验证码', max_length=20, verbose_name='验证码类型'),
        ),
    ]
