# Generated by Django 6.0.3 on 2026-03-15 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='密钥名称')),
                ('key', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='API密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('rate_limit_per_minute', models.IntegerField(default=60, verbose_name='每分钟限制')),
                ('rate_limit_per_day', models.IntegerField(default=1000, verbose_name='每日限制')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'API密钥',
                'verbose_name_plural': 'API密钥',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='APIService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='服务名称')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='标识')),
                ('description', models.TextField(verbose_name='服务描述')),
                ('category', models.CharField(choices=[('ai', '人工智能'), ('data', '数据服务'), ('tools', '工具服务'), ('social', '社交服务'), ('other', '其他')], default='other', max_length=50, verbose_name='分类')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('deprecated', '已废弃')], default='draft', max_length=20, verbose_name='状态')),
                ('base_url', models.URLField(verbose_name='基础URL')),
                ('documentation_url', models.URLField(blank=True, verbose_name='文档URL')),
                ('version', models.CharField(default='1.0.0', max_length=50, verbose_name='版本号')),
                ('price_per_call', models.DecimalField(decimal_places=6, default=0.0, max_digits=10, verbose_name='每次调用价格')),
                ('free_calls_per_day', models.IntegerField(default=100, verbose_name='每日免费调用次数')),
                ('is_public', models.BooleanField(default=True, verbose_name='公开可见')),
                ('is_paid', models.BooleanField(default=False, verbose_name='付费服务')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API服务',
                'verbose_name_plural': 'API服务',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, verbose_name='路径')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10, verbose_name='请求方法')),
                ('summary', models.CharField(max_length=500, verbose_name='接口简介')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('request_example', models.TextField(blank=True, verbose_name='请求示例')),
                ('response_example', models.TextField(blank=True, verbose_name='响应示例')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='apigateway.apiservice', verbose_name='所属服务')),
            ],
            options={
                'verbose_name': 'API端点',
                'verbose_name_plural': 'API端点',
                'ordering': ['path'],
                'unique_together': {('service', 'path', 'method')},
            },
        ),
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('request_url', models.URLField(verbose_name='请求URL')),
                ('request_headers', models.JSONField(blank=True, null=True, verbose_name='请求头')),
                ('request_body', models.TextField(blank=True, verbose_name='请求体')),
                ('response_status', models.IntegerField(verbose_name='响应状态码')),
                ('response_headers', models.JSONField(blank=True, null=True, verbose_name='响应头')),
                ('response_body', models.TextField(blank=True, verbose_name='响应体')),
                ('execution_time', models.FloatField(verbose_name='执行时间(秒)')),
                ('call_time', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apigateway.apiendpoint', verbose_name='端点')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='apigateway.apikey', verbose_name='API密钥')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='apigateway.apiservice', verbose_name='服务')),
            ],
            options={
                'verbose_name': 'API调用日志',
                'verbose_name_plural': 'API调用日志',
                'ordering': ['-call_time'],
            },
        ),
    ]
