# Generated by Django 5.2 on 2026-03-13 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.CharField(choices=[('wechat', '微信'), ('qq', 'QQ'), ('weibo', '微博'), ('github', 'GitHub'), ('google', 'Google'), ('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=20, unique=True, verbose_name='第三方平台')),
                ('app_id', models.CharField(max_length=200, verbose_name='应用ID')),
                ('app_secret', models.CharField(max_length=200, verbose_name='应用密钥')),
                ('redirect_uri', models.URLField(blank=True, verbose_name='回调地址')),
                ('scope', models.CharField(blank=True, max_length=200, verbose_name='权限范围')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='额外配置')),
            ],
            options={
                'verbose_name': 'OAuth应用配置',
                'verbose_name_plural': 'OAuth应用配置',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='SocialLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.CharField(choices=[('wechat', '微信'), ('qq', 'QQ'), ('weibo', '微博'), ('github', 'GitHub'), ('google', 'Google'), ('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=20, verbose_name='第三方平台')),
                ('openid', models.CharField(blank=True, max_length=100, verbose_name='第三方唯一标识')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=10, verbose_name='状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_login_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '第三方登录日志',
                'verbose_name_plural': '第三方登录日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.CharField(choices=[('wechat', '微信'), ('qq', 'QQ'), ('weibo', '微博'), ('github', 'GitHub'), ('google', 'Google'), ('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=20, verbose_name='第三方平台')),
                ('openid', models.CharField(max_length=100, verbose_name='第三方唯一标识')),
                ('unionid', models.CharField(blank=True, max_length=100, verbose_name='联合ID')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='昵称')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
                ('access_token', models.TextField(blank=True, verbose_name='访问令牌')),
                ('refresh_token', models.TextField(blank=True, verbose_name='刷新令牌')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '第三方账号',
                'verbose_name_plural': '第三方账号',
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'openid')},
            },
        ),
    ]
